"""initial schema

Revision ID: 9b1f8cee2bb6
Revises:
Create Date: 2026-07-28 22:59:07.624485

"""

from collections.abc import Sequence

import sqlalchemy as sa

# Autogenerate emits sqlmodel.sql.sqltypes.AutoString() for every str column.
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9b1f8cee2bb6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "phrase",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "difficulty",
            sa.Enum("easy", "medium", "hard", name="difficulty", native_enum=False),
            nullable=False,
        ),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_phrase")),
    )
    op.create_index(op.f("ix_phrase_category"), "phrase", ["category"], unique=False)
    op.create_index(
        op.f("ix_phrase_difficulty"), "phrase", ["difficulty"], unique=False
    )
    op.create_index(op.f("ix_phrase_text"), "phrase", ["text"], unique=True)
    op.create_table(
        "attempt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("phrase_id", sa.Integer(), nullable=False),
        sa.Column("transcript", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column(
            "word_feedback", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("audio_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["phrase_id"], ["phrase.id"], name=op.f("fk_attempt_phrase_id_phrase")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attempt")),
    )
    op.create_index(
        op.f("ix_attempt_created_at"), "attempt", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_attempt_phrase_id"), "attempt", ["phrase_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_attempt_phrase_id"), table_name="attempt")
    op.drop_index(op.f("ix_attempt_created_at"), table_name="attempt")
    op.drop_table("attempt")
    op.drop_index(op.f("ix_phrase_text"), table_name="phrase")
    op.drop_index(op.f("ix_phrase_difficulty"), table_name="phrase")
    op.drop_index(op.f("ix_phrase_category"), table_name="phrase")
    op.drop_table("phrase")
    # ### end Alembic commands ###
