from alembic import command
from alembic.config import Config

from app import config


def test_migrations_match_the_models(database):
    """`alembic check` fails when a model change never got a migration.

    This is the guard that makes it safe to have dropped create_all() from the
    lifespan: schema drift now surfaces as a red test rather than as a missing
    column at runtime. The `database` fixture has already upgraded to head, so
    what's being compared is head-vs-models.
    """
    alembic_config = Config(str(config.BASE_DIR / "alembic.ini"))
    alembic_config.attributes["configure_logger"] = False
    command.check(alembic_config)  # raises AutogenerateDiffsDetected on drift
